window.INSIDE_PROMPT_CATEGORIES = [
  { id: 'daily-check-in', name: 'Daily Check-in', label: '日常感受' },
  { id: 'emotion', name: 'Emotion', label: '情绪' },
  { id: 'self-discovery', name: 'Self Discovery', label: '自我发现' },
  { id: 'relationship', name: 'Relationship', label: '关系' },
  { id: 'work-growth', name: 'Work & Growth', label: '工作与成长' },
  { id: 'decision-making', name: 'Decision Making', label: '选择与决定' },
  { id: 'gratitude', name: 'Gratitude', label: '感激' },
  { id: 'future-vision', name: 'Future Vision', label: '未来想象' }
];

window.INSIDE_PROMPTS = [
  { id: 'daily-001', category: 'daily-check-in', text: '今天有什么还留在你脑子里？', tags: ['daily', 'unfinished'], depth: 'gentle', active: true },
  { id: 'daily-002', category: 'daily-check-in', text: '今天有哪个瞬间，你后来又想起了？', tags: ['moment', 'memory'], depth: 'gentle', active: true },
  { id: 'daily-003', category: 'daily-check-in', text: '今天有没有一件小事，比想象中更影响你？', tags: ['daily', 'impact'], depth: 'gentle', active: true },
  { id: 'daily-004', category: 'daily-check-in', text: '如果把今天慢慢倒带，你想停在哪一刻？', tags: ['moment', 'reflection'], depth: 'gentle', active: true },
  { id: 'daily-005', category: 'daily-check-in', text: '今天有什么话，你没有机会好好说完？', tags: ['unspoken', 'daily'], depth: 'medium', active: true },
  { id: 'daily-006', category: 'daily-check-in', text: '此刻的你，最想先放下哪一件事？', tags: ['release', 'present'], depth: 'gentle', active: true },
  { id: 'daily-007', category: 'daily-check-in', text: '今天什么事情消耗了你，什么事情又让你恢复了一点？', tags: ['energy', 'daily'], depth: 'medium', active: true },
  { id: 'daily-008', category: 'daily-check-in', text: '如果今天只留下一句话，你会留下什么？', tags: ['daily', 'meaning'], depth: 'gentle', active: true },

  { id: 'emotion-001', category: 'emotion', text: '最近有什么感受，你一直没有好好承认？', tags: ['awareness', 'unspoken'], depth: 'medium', active: true },
  { id: 'emotion-002', category: 'emotion', text: '哪一种情绪最近常常回来找你？', tags: ['repeating', 'awareness'], depth: 'gentle', active: true },
  { id: 'emotion-003', category: 'emotion', text: '最近哪件事让你的反应，比自己预想的更强烈？', tags: ['trigger', 'reaction'], depth: 'medium', active: true },
  { id: 'emotion-004', category: 'emotion', text: '如果不用解释这份感受，它现在最像什么？', tags: ['felt-sense', 'awareness'], depth: 'medium', active: true },
  { id: 'emotion-005', category: 'emotion', text: '有什么情绪，你习惯很快把它压下去？', tags: ['avoidance', 'pattern'], depth: 'deep', active: true },
  { id: 'emotion-006', category: 'emotion', text: '最近一次感到轻松，发生在什么时候？', tags: ['relief', 'moment'], depth: 'gentle', active: true },
  { id: 'emotion-007', category: 'emotion', text: '你现在最需要被允许拥有哪一种感受？', tags: ['permission', 'need'], depth: 'deep', active: true },
  { id: 'emotion-008', category: 'emotion', text: '有哪种说不清的感觉，正在提醒你注意什么？', tags: ['signal', 'awareness'], depth: 'deep', active: true },

  { id: 'self-001', category: 'self-discovery', text: '最近你在哪件事上，看见了一个不太熟悉的自己？', tags: ['identity', 'change'], depth: 'medium', active: true },
  { id: 'self-002', category: 'self-discovery', text: '如果不考虑别人怎么看，你会怎样描述现在的自己？', tags: ['identity', 'expectation'], depth: 'deep', active: true },
  { id: 'self-003', category: 'self-discovery', text: '有什么你一直以为自己应该喜欢，其实并不喜欢？', tags: ['preference', 'expectation'], depth: 'medium', active: true },
  { id: 'self-004', category: 'self-discovery', text: '最近什么事情让你觉得：原来我已经改变了？', tags: ['change', 'growth'], depth: 'gentle', active: true },
  { id: 'self-005', category: 'self-discovery', text: '你最希望别人理解你的哪一部分？', tags: ['identity', 'understanding'], depth: 'medium', active: true },
  { id: 'self-006', category: 'self-discovery', text: '你正在努力成为谁，又在害怕失去谁？', tags: ['identity', 'change'], depth: 'deep', active: true },
  { id: 'self-007', category: 'self-discovery', text: '有什么评价，你已经不想再用来定义自己？', tags: ['identity', 'belief'], depth: 'deep', active: true },
  { id: 'self-008', category: 'self-discovery', text: '在哪些时刻，你最像真正的自己？', tags: ['authenticity', 'identity'], depth: 'medium', active: true },

  { id: 'relationship-001', category: 'relationship', text: '最近哪段关系，让你心里有一些没有说完的话？', tags: ['unspoken', 'connection'], depth: 'medium', active: true },
  { id: 'relationship-002', category: 'relationship', text: '有没有一个人，你希望他更理解你什么？', tags: ['understanding', 'need'], depth: 'gentle', active: true },
  { id: 'relationship-003', category: 'relationship', text: '最近一次关系里的不舒服，真正触碰了你什么？', tags: ['conflict', 'trigger'], depth: 'deep', active: true },
  { id: 'relationship-004', category: 'relationship', text: '你正在一段关系里迁就什么？', tags: ['boundary', 'pattern'], depth: 'medium', active: true },
  { id: 'relationship-005', category: 'relationship', text: '有什么期待，你从没有清楚地告诉过对方？', tags: ['expectation', 'communication'], depth: 'deep', active: true },
  { id: 'relationship-006', category: 'relationship', text: '哪一段关系，最近让你感到被看见？', tags: ['connection', 'support'], depth: 'gentle', active: true },
  { id: 'relationship-007', category: 'relationship', text: '你想靠近谁，又为什么有一点退缩？', tags: ['closeness', 'fear'], depth: 'medium', active: true },
  { id: 'relationship-008', category: 'relationship', text: '在重要的关系里，你最容易忽略自己的什么需要？', tags: ['need', 'pattern'], depth: 'deep', active: true },

  { id: 'work-001', category: 'work-growth', text: '最近工作中什么事情，让你反复想到？', tags: ['work', 'unfinished'], depth: 'gentle', active: true },
  { id: 'work-002', category: 'work-growth', text: '你最近在努力证明什么，又是向谁证明？', tags: ['recognition', 'pattern'], depth: 'deep', active: true },
  { id: 'work-003', category: 'work-growth', text: '最近哪件事让你感到自己的成长？', tags: ['growth', 'progress'], depth: 'gentle', active: true },
  { id: 'work-004', category: 'work-growth', text: '现在的工作里，什么在消耗你，什么仍然吸引你？', tags: ['energy', 'meaning'], depth: 'medium', active: true },
  { id: 'work-005', category: 'work-growth', text: '如果不害怕让人失望，你会怎样安排自己的工作？', tags: ['boundary', 'expectation'], depth: 'deep', active: true },
  { id: 'work-006', category: 'work-growth', text: '你现在最想提升的，真的是能力，还是信心？', tags: ['growth', 'confidence'], depth: 'medium', active: true },
  { id: 'work-007', category: 'work-growth', text: '最近哪个反馈让你难以放下？', tags: ['feedback', 'recognition'], depth: 'medium', active: true },
  { id: 'work-008', category: 'work-growth', text: '你希望自己的工作，最终为生活留下什么？', tags: ['meaning', 'vision'], depth: 'deep', active: true },

  { id: 'decision-001', category: 'decision-making', text: '最近有什么选择，一直悬而未决？', tags: ['choice', 'uncertainty'], depth: 'gentle', active: true },
  { id: 'decision-002', category: 'decision-making', text: '在这份犹豫里，你最不愿意失去什么？', tags: ['choice', 'value'], depth: 'medium', active: true },
  { id: 'decision-003', category: 'decision-making', text: '如果没有人评价你的决定，你会更倾向哪一边？', tags: ['choice', 'expectation'], depth: 'deep', active: true },
  { id: 'decision-004', category: 'decision-making', text: '你是在等待更多信息，还是在等待确定感？', tags: ['uncertainty', 'pattern'], depth: 'medium', active: true },
  { id: 'decision-005', category: 'decision-making', text: '这个决定里，哪一种后悔更难承受？', tags: ['regret', 'choice'], depth: 'deep', active: true },
  { id: 'decision-006', category: 'decision-making', text: '如果只做一个很小的下一步，你会做什么？', tags: ['action', 'choice'], depth: 'gentle', active: true },
  { id: 'decision-007', category: 'decision-making', text: '你真正想选择的，和你觉得应该选择的，有什么不同？', tags: ['desire', 'expectation'], depth: 'deep', active: true },
  { id: 'decision-008', category: 'decision-making', text: '这个选择最想保护你生活里的什么？', tags: ['value', 'choice'], depth: 'medium', active: true },

  { id: 'gratitude-001', category: 'gratitude', text: '今天有什么微小的事情，值得你停下来记住？', tags: ['daily', 'appreciation'], depth: 'gentle', active: true },
  { id: 'gratitude-002', category: 'gratitude', text: '最近谁做的一件小事，让你感到被照顾？', tags: ['relationship', 'support'], depth: 'gentle', active: true },
  { id: 'gratitude-003', category: 'gratitude', text: '最近有什么曾经习以为常的事，让你重新珍惜？', tags: ['appreciation', 'awareness'], depth: 'medium', active: true },
  { id: 'gratitude-004', category: 'gratitude', text: '过去的自己，做过什么值得现在的你感谢？', tags: ['self', 'growth'], depth: 'medium', active: true },
  { id: 'gratitude-005', category: 'gratitude', text: '最近哪一个普通瞬间，让你觉得生活还不错？', tags: ['moment', 'daily'], depth: 'gentle', active: true },
  { id: 'gratitude-006', category: 'gratitude', text: '有什么支持一直都在，只是你最近才看见？', tags: ['support', 'awareness'], depth: 'medium', active: true },
  { id: 'gratitude-007', category: 'gratitude', text: '你的身体今天替你完成了什么？', tags: ['body', 'appreciation'], depth: 'gentle', active: true },
  { id: 'gratitude-008', category: 'gratitude', text: '此刻你最想认真说一声谢谢的，是什么？', tags: ['appreciation', 'meaning'], depth: 'gentle', active: true },

  { id: 'future-001', category: 'future-vision', text: '如果一年后的生活更接近你想要的样子，会有什么不同？', tags: ['vision', 'life'], depth: 'medium', active: true },
  { id: 'future-002', category: 'future-vision', text: '你希望未来的自己，感谢现在的你做了什么？', tags: ['action', 'future'], depth: 'gentle', active: true },
  { id: 'future-003', category: 'future-vision', text: '有什么愿望，你很少认真允许自己想象？', tags: ['desire', 'permission'], depth: 'deep', active: true },
  { id: 'future-004', category: 'future-vision', text: '如果不必急着成功，你想慢慢建立怎样的生活？', tags: ['life', 'pace'], depth: 'medium', active: true },
  { id: 'future-005', category: 'future-vision', text: '你正在走向的未来，是自己选择的，还是顺势接受的？', tags: ['choice', 'direction'], depth: 'deep', active: true },
  { id: 'future-006', category: 'future-vision', text: '未来有什么变化，让你期待，也让你有一点害怕？', tags: ['change', 'fear'], depth: 'medium', active: true },
  { id: 'future-007', category: 'future-vision', text: '你希望三年后的日常，拥有怎样的节奏？', tags: ['daily', 'pace'], depth: 'gentle', active: true },
  { id: 'future-008', category: 'future-vision', text: '现在做的哪些事情，正在悄悄塑造你的未来？', tags: ['action', 'awareness'], depth: 'medium', active: true }
];
